language: csharp
solution:Medidata.MAuth.sln 
mono: none
dist: xenial
dotnet: 3.0.100
install:
  - dotnet tool install --global dotnet-sonarscanner --version 4.8.0
  - dotnet tool install --global coverlet.console
script:
  - dotnet restore --source "https://api.nuget.org/v3/index.json" --source $MEDIDATA_NUGET_SOURCE --verbosity m
  - dotnet build ./tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj --verbosity m
  - coverlet ./tests/Medidata.MAuth.Tests/bin/Debug/netcoreapp1.1/Medidata.MAuth.Tests.dll --target “dotnet” --targetargs “test” --format opencover
